{
 "title": "Apps Performance Comparison",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus ", "query": "prometheus" },
   { "name": "loki_ds", "label": "Loki", "query": "loki" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "app1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app1\"} |= ``"
    }
   ]
  },
  {
   "title": "app2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"app2\"} |= ``"
    }
   ]
  },
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_requests_per_second",
     "legendFormat": "RPS - {{job}}"
    }
   ]
  },
  {
   "title": "HTTP Status app1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(traefik_router_requests_total{job=\"traefik\", service=\"app1@docker\"}[$__interval])",
     "legendFormat": "{{code}} - {{service}}"
    }
   ]
  },
  {
   "title": "HTTP Status app2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(traefik_router_requests_total{job=\"traefik\", service=\"app2@docker\"}[$__interval])",
     "legendFormat": "{{code}} - {{service}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "systemruntime_cpu_usage_ratio", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory usage (working set)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_working_set_bytes",
     "legendFormat": "Working Set - {{job}}"
    },
    {
     "expr": "systemruntime_gc_heap_size_bytes",
     "legendFormat": "GC Heap Size - {{job}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "GC Generation Size app1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"app1\"}",
     "legendFormat": "Gen 0 size - {{job}}"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{job=\"app1\"}",
     "legendFormat": "Gen 1 size - {{job}}"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{job=\"app1\"}",
     "legendFormat": "Gen 2 size - {{job}}"
    },
    {
     "expr": "systemruntime_poh_size_bytes{job=\"app1\"}",
     "legendFormat": "POH size - {{job}}"
    },
    {
     "expr": "systemruntime_loh_size_bytes{job=\"app1\"}",
     "legendFormat": "LOH size - {{job}}"
    }
   ]
  },
  {
   "title": "GC Generation Size app2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"app2\"}",
     "legendFormat": "Gen 0 size - {{job}}"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{job=\"app2\"}",
     "legendFormat": "Gen 1 size - {{job}}"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{job=\"app2\"}",
     "legendFormat": "Gen 2 size - {{job}}"
    },
    {
     "expr": "systemruntime_poh_size_bytes{job=\"app2\"}",
     "legendFormat": "POH size - {{job}}"
    },
    {
     "expr": "systemruntime_loh_size_bytes{job=\"app2\"}",
     "legendFormat": "LOH size - {{job}}"
    }
   ]
  },
  {
   "title": "GC Count app1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_gc_count{job=\"app1\"}",
     "legendFormat": "Gen 0 GC count - {{job}}"
    },
    {
     "expr": "systemruntime_gen_1_gc_count{job=\"app1\"}",
     "legendFormat": "Gen 1 GC count - {{job}}"
    },
    {
     "expr": "systemruntime_gen_2_gc_count{job=\"app1\"}",
     "legendFormat": "Gen 2 GC count - {{job}}"
    }
   ]
  },
  {
   "title": "GC Count app2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "systemruntime_gen_0_gc_count{job=\"app2\"}",
     "legendFormat": "Gen 0 GC count - {{job}}"
    },
    {
     "expr": "systemruntime_gen_1_gc_count{job=\"app2\"}",
     "legendFormat": "Gen 1 GC count - {{job}}"
    },
    {
     "expr": "systemruntime_gen_2_gc_count{job=\"app2\"}",
     "legendFormat": "Gen 2 GC count - {{job}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{job=\"app1\"}",
     "legendFormat": "GC Fragmentation"
    },
    {
     "expr": "systemruntime_gc_fragmentation_ratio{job=\"app2\"}",
     "legendFormat": "GC Fragmentation"
    }
   ]
  },
  {
   "title": "Allocation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes",
     "legendFormat": "Allocation rate bytes - {{job}}"
    }
   ]
  },
  {
   "title": "Time in GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio",
     "legendFormat": "% Time in GC since last GC - {{job}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    { "expr": "systemruntime_exception_count", "legendFormat": "Exception Count - {{job}}" }
   ]
  }
 ]
}